# Generated by Django 5.0.3 on 2024-05-16 21:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_address_user_created_at_user_date_of_birth_and_more'),
    ]

    operations = [
        #migrations.RemoveField(
          #  model_name='item',
          #  name='location',
         #),
        #migrations.RemoveField(
         #   model_name='item',
         #  name='rental_price',
        #),
        #migrations.RemoveField(
         #   model_name='item',
         #   name='status',
        #),
        #migrations.AddField(
         #   model_name='item',
         #  name='available',
         #   field=models.BooleanField(default=True),
        #),
        #migrations.AddField(
         #   model_name='item',
         #   name='created_at',
         #   field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
        #    preserve_default=False,
        #),
        #migrations.AddField(
        #    model_name='item',
        #    name='name',
        #    field=models.CharField(default='2022-01-01 00:00:00', max_length=100),
        #    preserve_default=False,
        #),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
            
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user'),
        ),
    ]
